name: Update jira on commit

on:
  push

jobs:
  update-jira:
    runs-on: self-hosted
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Echo github context
        env:
            GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
            echo "$GITHUB_CONTEXT"

      - name: Install Python
        uses: actions/setup-python@v2

      - name: Install dependencies
        run: pip install jira

      - name: Run Jira script
        run: |
            python .github/scripts/jira_integration.py ${{ secrets.JIRA_USER_EMAIL }} ${{ secrets.JIRA_PASSWORD }} '${{ toJson(github) }}'

        # - name: Test regex
        # run: |
        #     if [[ "${{github.event.head_commit.message}}" =~ ^STAR-[0-9]+(.|\n)*? ]];
        #     then
        #         echo "Commit message '${{github.event.head_commit.message}}' has jira key"
        #     else
        #         echo "Commit message '${{github.event.head_commit.message}}' doesnt have jira key"
        #     fi