name: Update jira on commit

on:
  push

jobs:
  update-jira:
    if: ${{github.event.head_commit.message}} =~ STAR-[0-9]+
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Echo event
        env:
            GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
            echo "GITHUB_CONTEXT"
            echo github.event.commits.message
    
      - name: Test regex conditional
        run: |
            if [[ "${{github.event.head_commit.message}}" =~ ^STAR-[0-9]+(.|\n)*?$ ]];
            then
                echo "Commit message has jira key"
            fi