name: Update jira on commit

on:
  push

jobs:
  update-jira:
    if: ${{github.event.head_commit.message}} =~ ^(?i)STAR-[0-9]+(.|\n)*?$
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Echo event
        env:
            GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
            echo "GITHUB_CONTEXT"
            echo github.event.commits.message
    
      - name: Test regex conditional
        run: |
            if [[ "${{github.event.head_commit.message}}" =~ ^(?i)STAR-[0-9]+(.|\n)*? ]];
            then
                echo "Commit message '${{github.event.head_commit.message}}' has jira key"
            else
                echo "Commit message '${{github.event.head_commit.message}}' doesnt have jira key"
            fi